config/routes.rb
Rails.application.routes.draw do
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get 'lists/new'
  get 'top' => 'home#top'
  resources :lists#今まで記述したものこれ一つで完了
  #post 'lists' => 'lists#create'
  #get 'lists' => 'lists#index'
  # .../lists/1 や .../lists/3 に該当する
  #get 'lists/:id' => 'lists#show', as: 'list'#←に書き換えget 'lists/:id' => 'lists#show'
  #get 'lists/:id/edit' => 'lists#edit', as: 'edit_list'
  #patch 'lists/:id' => 'lists#update', as: 'update_list'
  #delete 'lists/:id' => 'lists#destroy', as: 'destroy_list'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
   has_one_attached :image

   #以下追加
   validates :title, presence: true
   validates :body, presence: true
   validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @list = List.new
  end

# 以下を追加
  def create
     # １.&2. データを受け取り新規登録するためのインスタンス作成
    #list = List.new(list_params)
     # 3. データをデータベースに保存するためのsaveメソッド実行
    #list.save
     # 4. トップ画面へリダイレクト
     #redirect_to '/top'以下に変更
    #redirect_to list_path(list.id)

    #上記を下記に書き換え

    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
     @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)
  end

  def destroy
    list = List.find(params[:id])  # データ（レコード）を1件取得
    list.destroy  # データ（レコード）を削除
    redirect_to '/lists'  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ
  def list_params
    params.require(:list).permit(:title, :body, :image)#:imageを追加
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>
<%= form_with model: @list do |f| %>
<!--%= form_with model: @list, url: update_list_path(@list.id), method: :patch do |f| %>を↑に書き換え-->
<!--%= form_with model: @list do |f| %>を↑に書き換え-->

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '保存' %>

<% end %>

app/views/lists/index.html.erb
<h1>投稿一覧</h1>

<!--%= @lists.each do |list| %>-->
<% @lists.each do |list| %><!--@listsの前に＝がない-->

  <p>タイトル</p>
  <!--<span>%= list.title, %></span>↓に変更-->
  <span>
    <%= link_to list.title, "/lists/#{list.id}" %>
  </span>

  <p>画像</p>
  <% if list.image.attached? %><!--エラー回避-->
    <%= image_tag list.image, size: "200x200" %><!--表示される画像-->
  <% else %><!--エラー回避-->
    <%= image_tag 'no_image', size: "200x200" %><!--エラー回避(表示されないときの代わりのもの)-->
  <% end %>
<% end %>

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<!--以下追加-->
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<!-- form_with部分 -->
<!-- form_withにオプション追記 -->
<%= form_with model: @list, url: '/lists', method: :post do |f| %>
<!-- ↑こちらに書き換え%= form_with model: @list do |f| %>←反対側にもある -->
<!-- ↑こちらに書き換え%= form_with model: List.new do |f| %>←反対側にもある -->
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <!-- 追加部分 -->
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <%= f.submit '投稿' %>
<% end %>

app/views/lists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>

<h2>本文</h2>
<p><%= @list.body %></p>

<h2>画像</h2>
<% if @list.image.attached? %>
  <%= image_tag @list.image, size: "300x300" %>
<% else %>
  <%= image_tag 'no_image', size: "300x300" %>
<% end %>

<%= link_to "編集", edit_list_path(@list.id) %><!--この行追加-->
<!--%= link_to "削除", destroy_list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>を以下に書き換え-->
<%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>